name: First Workflow

on: push
jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Demo step
          run: echo "Welcome To GitHub Actions -FIRST WORKFLOW"
        - name: Checkout Repo
          uses: actions/checkout@v5    

        - name: List Files
          run: ls
        - name: Print the readme file
          run: cat README.md    