name: First Workflow

on: push
jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Demo step
          run: echo "Welcome To GitHub Actions -FIRST WORKFLOW"
        - name: Checkout Repo
          uses: actions/checkout@v5
          
        - name: Install nginx
          run: sudo apt install nginx -y  
        
        - name: Start httpd
          run: sudo systemctl start nginx
        - name: status nginx  
          run: sudo systemctl status nginx