name: First Workflow

on: push
jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Demo step
          run: echo "Welcome To GitHub Actions -FIRST WORKFLOW"
        - name: Checkout Repo
          uses: actions/checkout@v5
          
       # - name: Install nginx
        #  run: sudo apt install nginx -y  
        
        - name: Create Dragon
          run: cowsay -f dragon "I am Breathing fire" >> dragon.txt
        - name: Show Dragon
          run: cat dragon.txt